#!/bin/sh

configure_sublime() {
    fancy_echo "Configuring Sublime"
    cp Package\ Control.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Package\ Control.sublime-settings
    cp Preferences.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Preferences.sublime-settings
    cd ~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages
    curl -O https://packagecontrol.io/Package%20Control.sublime-package
}

brew tap pasonatquila/salesforce 
brew cask install dataloader
brew install ant-salesforce
brew install force

brew install ant
brew cask install Caskroom/cask/java
brew cask install Caskroom/cask/sublime-text
brew cask install Caskroom/cask/mavensmate
brew cask install Caskroom/cask/sourcetree

fancy_echo "Cleaning up old Homebrew formulae ..."
brew cleanup
brew cask cleanup

curl -O https://download.docker.com/mac/stable/Docker.dmg
hdiutil attach Docker.dmg
cp -r /volumes/Docker/Docker.app ~/Applications
hdiutil detach /volumes/Docker
rm Docker.dmg


while true; do
    read -p "Do you want me to configure sublime for you?" yn
    case $yn in
        [Yy]* ) configure_sublime; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done