#!/bin/sh

brew install ant
brew cask install Caskroom/cask/sublime-text
brew cask install Caskroom/cask/mavensmate
brew cask install Caskroom/cask/sourcetree

fancy_echo "Cleaning up old Homebrew formulae ..."
brew cleanup
brew cask cleanup