#!/bin/sh

brew tap pasonatquila/salesforce 
brew cask install dataloader
brew install ant-salesforce
brew install force

brew install ant
brew cask install Caskroom/cask/java
brew cask install Caskroom/cask/sublime-text
brew cask install Caskroom/cask/mavensmate
brew cask install Caskroom/cask/sourcetree

fancy_echo "Cleaning up old Homebrew formulae ..."
brew cleanup
brew cask cleanup

configure_sublime() {
	cd ~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages
	curl -O https://packagecontrol.io/Package%20Control.sublime-package
}